version: '3.3'
services:
  db:
    image: postgres:15
    restart: always
    # Starts the DB with a max number of connections of 50
    command: postgres -c 'log_statement=all' -c 'log_connections=true' -c 'log_disconnections=true' -c 'max_connections=50'
    container_name: rk_db_dev
    ports:
      - '5444:5432'
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdatabase:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'rk-dev-db'
      POSTGRES_PASSWORD: 'bloublou123'
volumes:
  pgdatabase:
