// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaXOqfApTxFwqFfmtkzSpgJtw_sIJAsb0',
    appId: '1:492137530634:web:93bd4e61dea6c9b8b3a6f3',
    messagingSenderId: '492137530634',
    projectId: 'receipt-keeper-9abac',
    authDomain: 'receipt-keeper-9abac.firebaseapp.com',
    storageBucket: 'receipt-keeper-9abac.appspot.com',
    measurementId: 'G-QY4GLGCNF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMWaF6VGEfSEyRNHr2BViCOWTrJYNOEPc',
    appId: '1:492137530634:android:2563873155cb992db3a6f3',
    messagingSenderId: '492137530634',
    projectId: 'receipt-keeper-9abac',
    storageBucket: 'receipt-keeper-9abac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4iiw3q7vxDQXuMvb72ae6q1pHqsADjhA',
    appId: '1:492137530634:ios:6f436d431fd16592b3a6f3',
    messagingSenderId: '492137530634',
    projectId: 'receipt-keeper-9abac',
    storageBucket: 'receipt-keeper-9abac.appspot.com',
    iosClientId: '492137530634-1lobt5ii63tm1ejp7ri0lstk6hbrtco9.apps.googleusercontent.com',
    iosBundleId: 'dev.yueh.receiptKeeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4iiw3q7vxDQXuMvb72ae6q1pHqsADjhA',
    appId: '1:492137530634:ios:6f436d431fd16592b3a6f3',
    messagingSenderId: '492137530634',
    projectId: 'receipt-keeper-9abac',
    storageBucket: 'receipt-keeper-9abac.appspot.com',
    iosClientId: '492137530634-1lobt5ii63tm1ejp7ri0lstk6hbrtco9.apps.googleusercontent.com',
    iosBundleId: 'dev.yueh.receiptKeeper',
  );
}
